version: '3'

services:

  webservergo:
      build: .
      ports: 
          - 8080:8080
      

  nginx:
    image: nginx
    volumes: 
        - ./nginx:/usr/share/nginx/html
    ports:
        - 8083:80

